=== Gryneon/ParserLib/Parser/Schemas/Spec.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="Parser/Spec" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="Parser/Spec">
  <xs:include schemaLocation="Types.xsd"/>
  <xs:element name="Spec">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="NonEmptyTokenType"/>
        <xs:element name="TextFile" type="xs:boolean"/>
        <xs:element name="TokenRules" type="RuleList" minOccurs="0"/>
        <xs:element name="GroupTokenRules" type="RuleList" minOccurs="0"/>
        <xs:element name="TokenLookups" type="TokenLookupsType" minOccurs="0"/>
        <xs:element name="Instructions" minOccurs="0">
          <xs:complexType>
            <xs:sequence>   
              <xs:choice maxOccurs="unbounded">
                <xs:element name="GotoOpIndex">
                  <xs:complexType>
                    <xs:attributeGroup ref="TargetAttrGroup"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="GotoLabel" type="RequiredNameType"/>
                <xs:element name="Label" type="RequiredNameType"/>
                <xs:element name="Divide">
                  <xs:complexType>
                    <xs:attribute name="output_var" use="required" type="DataKeyType"/>
                    <xs:attribute name="dividend_var" use="optional" type="DataKeyType"/>
                    <xs:attribute name="divisor_var" use="optional" type="DataKeyType"/>
                    <xs:attribute name="dividend" use="optional" type="xs:int"/>
                    <xs:attribute name="divisor" use="optional" type="xs:int"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="Multiply">
                  <xs:complexType>
                    <xs:attribute name="output_var" use="required" type="DataKeyType"/>
                    <xs:attribute name="left_var" use="optional" type="DataKeyType"/>
                    <xs:attribute name="right_var" use="optional" type="DataKeyType"/>
                    <xs:attribute name="left" use="optional" type="xs:int"/>
                    <xs:attribute name="right" use="optional" type="xs:int"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="MakeCursor">
                  <xs:complexType>
                    <xs:attribute name="cursor_var" use="required" type="DataKeyType"/>
                    <xs:attribute name="list_var" use="optional" type="DataKeyType"/>
                    <xs:attributeGroup ref="PositionAttrGroup"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="SetCursorPos">
                  <xs:complexType>
                    <xs:attribute name="cursor_var" use="required" type="DataKeyType"/>
                    <xs:attributeGroup ref="PositionAttrGroup"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="ExtOperation">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="Parameter" maxOccurs="unbounded">
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="xs:string">
                              <xs:attribute name="type" type="xs:token"/>
                            </xs:extension>
                          </xs:simpleContent>
                        </xs:complexType>
                      </xs:element>
                    </xs:sequence>
                    <xs:attribute name="name" use="required" type="NonEmptyTokenType"/>
                    <xs:attribute name="input_var" use="optional" type="DataKeyType"/>
                    <xs:attribute name="output_var" use="optional" type="DataKeyType"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="Terminate" type="SuccessType"/>
                <xs:element name="Initialize">
                  <xs:annotation>
                    <xs:documentation>
                      Initializes a collection type.
                    </xs:documentation>
                  </xs:annotation>
                  <xs:complexType>
                    <xs:attribute name="initial_var" use="required" type="DataKeyType"/>
                    <xs:attribute name="type" use="required" type="InitializeType">
                      <xs:annotation>
                        <xs:documentation>
                          The type of collection to make.
                        </xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value_type" use="required" type="NonEmptyTokenType">
                      <xs:annotation>
                        <xs:documentation>
                          The type of item in the collection.
                        </xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="key_type" use="optional" type="NonEmptyTokenType">
                      <xs:annotation>
                        <xs:documentation>
                          The type of key in the collection.
                          This is ignored unless needed.
                        </xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attributeGroup ref="PositionAttrGroup"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="Tokenize" type="InputOutputType"/>
                <xs:element name="TokenAssemble" type="InputOutputType"/>
                <xs:element name="ReadData">
                  <xs:complexType>
                    <xs:attribute name="content_var" use="optional" type="DataKeyType"/>
                    <xs:attribute name="output_var" use="required" type="DataKeyType"/>
                    <xs:attribute name="cursor_var" use="optional" type="DataKeyType"/>
                    <xs:attribute name="endian" use="optional" type="EndianessType"/>
                    <xs:attribute name="encoding" use="optional" type="EncodingType"/>
                    <xs:attributeGroup ref="DataTypeAttrGroup"/>
                    <xs:attributeGroup ref="LengthAttrGroup"/>
                    <xs:attributeGroup ref="PositionAttrGroup"/>
                  </xs:complexType>
                </xs:element>
                <xs:element name="ForCount">
                  <xs:complexType>
                    <xs:complexContent>
                      <xs:extension base="InnerInstructionSet">
                        <xs:attribute name="cursor_var" use="required" type="DataKeyType"/>
                        <xs:attributeGroup ref="LengthAttrGroup"/>
                      </xs:extension>
                    </xs:complexContent>
                  </xs:complexType>
                </xs:element>
                <xs:element name="ForEach">
                  <xs:complexType>
                    <xs:complexContent>
                      <xs:extension base="InnerInstructionSet">
                        <xs:attribute name="cursor_var" use="required" type="DataKeyType"/>
                      </xs:extension>
                    </xs:complexContent>
                  </xs:complexType>
                </xs:element>
                <xs:element name="AddItem" type="AddItemType"/>
                <xs:element name="IfBlock">
                  <xs:complexType>
                    <xs:sequence maxOccurs="unbounded" minOccurs="1">
                      <xs:element name="If" type="ConditionType" minOccurs="0" maxOccurs="unbounded"/>
                      <xs:element name="ElseIf" minOccurs="0" maxOccurs="unbounded" type="ConditionType"/>
                      <xs:element name="Else" minOccurs="0" maxOccurs="unbounded" type="InnerInstructionSet"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
                <xs:element name="While" type="ConditionType"/>
                <xs:element name="Until" type="ConditionType"/>
                <xs:element name="If" type="ConditionType"/>
                <xs:element name="Break" type="NoAttributesType"/>
                <xs:element name="Continue" type="NoAttributesType"/>
                <xs:element name="Print" type="DebugKeyType"/>
                <xs:element name="ToString" type="DebugKeyType"/>
                <xs:element name="Switch">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="Case" minOccurs="0" maxOccurs="unbounded" type="CaseInstructionSet"/>
                      <xs:element name="Default" minOccurs="0" maxOccurs="1" type="InnerInstructionSet"/>
                    </xs:sequence>
                    <xs:attributeGroup ref="ConditionAttrGroupSwitch"/>
                  </xs:complexType>
                </xs:element>
              </xs:choice>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="FileInferences" minOccurs="0" type="FileInferencesType"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="OpLabelKey">
      <xs:selector xpath=".//Label"/>
      <xs:field xpath="@name"/>
    </xs:key>
    
    <xs:key name="TokenCompatKey">
      <xs:selector xpath="TokenLookups/TokenLookup"/>
      <xs:field xpath="@alias"/>
    </xs:key>

    <xs:key name="SpecKey">
      <xs:selector xpath="Name"/>
      <xs:field xpath=""/>
    </xs:key>
    
    <xs:keyref refer="OpLabelKey" name="GotoLabelConstraint">
      <xs:selector xpath=".//GotoLabel"/>
      <xs:field xpath="@name"/>
    </xs:keyref>
    
  </xs:element>
</xs:schema>

=== Gryneon/ParserLib/Parser/Sample.xml
<?xml version="1.0" encoding="utf-8"?>
<Spec xmlns="Parser/Spec" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Parser\Spec ..\Parser\Schemas\Spec.xsd">
  <Name>wad_test</Name>
  <TextFile>false</TextFile>
  <Instructions>
    <Tokenize input_var="text" output_var="tokens"/>
    <Label name="Start"/>
    <MakeCursor cursor_var="current_pos" position="0"/>
    <GotoOpIndex target="2"/>
    <GotoLabel name="Start"/>
    <ReadData output_var="file_id" type="text" length="4" cursor_var="current_pos"/>
    <ReadData output_var="numlumps" type="int" cursor_var="current_pos"/>
    <ReadData output_var="diroffset" type="int" cursor_var="current_pos"/>  
    <SetCursorPos cursor_var="current_pos" position_var="diroffset"/>
    <Initialize initial_var="directory" type="Collection" value_type="DirectoryEntry"/>
    <ForCount length_var="numlumps" cursor_var="index">
      <ReadData output_var="lump_pos" type="int" cursor_var="current_pos"/>
      <ReadData output_var="lump_size" type="int" cursor_var="current_pos"/>
      <ReadData output_var="lump_name" type="text" length="8" cursor_var="current_pos"/>
      <ReadData output_var="lump_data" content_var="bytes" type="binary" length_var="lump_size" position_var="lump_pos"/>
      <AddItem name="directory" type="DirectoryEntry">lump_pos lump_size lump_name lump_data</AddItem>
    </ForCount>
    <ForEach cursor_var="cursor">
      <ReadData output_var="lump_pos" type="text" cursor_var="current_pos" length_var="current_item"/>
    </ForEach>
    <IfBlock>
      <If condition="[file_id] == {WAD2}">
        <!-- condition strings https://regex101.com/r/aTwSlR/1 -->
        <!-- <Initialize initial_var="s" type="Collection" value_type="d"/> -->
      </If>
      <ElseIf condition="[file_id] == {PACK}">
        <!-- PAK File -->
        <Initialize initial_var="s" type="Set" value_type="d"/>
      </ElseIf>
      <Else><!-- WAD File --></Else>
    </IfBlock>
    <Switch condition="[file_id]">
      <Case value="WAD2"/>
      <Default><!-- WAD File --></Default>
    </Switch>
    <Terminate success="true"/>
  </Instructions>
  <FileInferences initial="and">
    <Extension>wad</Extension>
    <Or>
      <Header>IWAD</Header>
      <Header>PWAD</Header>
    </Or>
  </FileInferences>
</Spec>

=== Gryneon/ParserLib/Parser/Specs/WAD2.xml
<?xml version="1.0" encoding="utf-8"?>
<Spec xmlns="Parser/Spec" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Parser\Spec ..\Schemas\Spec.xsd">
 
    <Name>wad2</Name>
    <TextFile>false</TextFile>
    <Instructions>
      <Label name="Start"/>
      <MakeCursor cursor_var="current_pos" list_var="bytes" position="0"/>
      <ReadData output_var="file_id" type="text" length="4" cursor_var="current_pos"/>
      <ReadData output_var="numlumps" type="int" cursor_var="current_pos"/>
      <ReadData output_var="diroffset" type="int" cursor_var="current_pos"/>
      <SetCursorPos cursor_var="current_pos" position_var="diroffset"/>
      <Initialize initial_var="directory" type="Collection" value_type="WadLump"/>
      <ForCount length_var="numlumps" cursor_var="index">
        <ReadData output_var="lump_pos" content_var="bytes" type="int" cursor_var="current_pos"/>
        <ReadData output_var="lump_dsize" content_var="bytes" type="int" cursor_var="current_pos"/>
        <ReadData output_var="lump_size" content_var="bytes" type="int" cursor_var="current_pos"/>
        <ReadData output_var="lump_type" content_var="bytes" type="byte" cursor_var="current_pos"/>
        <ReadData output_var="lump_cmprs" content_var="bytes" type="byte" cursor_var="current_pos"/>
        <ReadData output_var="lump_dummy" content_var="bytes" type="short" cursor_var="current_pos"/>
        <ReadData output_var="lump_name" content_var="bytes" type="text" length="16" cursor_var="current_pos"/>
        <ReadData output_var="lump_data" content_var="bytes" type="binary" length_var="lump_size" position_var="lump_pos"/>
        <AddItem name="directory" type="WadLump">lump_pos lump_size lump_name lump_data</AddItem>
      </ForCount>
      <Terminate success="true"/>
    </Instructions>

    <FileInferences initial="and">
      <Extension>wad</Extension>
      <Header>WAD2</Header>
    </FileInferences>
  </Spec>
